# Generated by Django 4.2 on 2024-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('report', models.ImageField(upload_to='report')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report',
            },
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine'},
        ),
    ]
