# Generated by Django 4.2 on 2024-03-26 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_medicine_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
