# Generated by Django 4.2 on 2024-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_medicine_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='batch',
            field=models.CharField(default='0000', max_length=55),
        ),
    ]
