# Generated by Django 4.2 on 2024-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_medicine_batch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine',
            new_name='Stocks',
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name': 'Stocks'},
        ),
    ]
