# Generated by Django 4.2 on 2024-04-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_rename_medicine_stocks_alter_stocks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ImageField(upload_to='prescription')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Prescription',
            },
        ),
    ]
