# Generated by Django 4.2 on 2024-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_doctorsprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
