# Generated by Django 4.2 on 2024-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprescription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
