# Generated by Django 4.2 on 2024-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_doctorsprescription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsprescription',
            old_name='notes',
            new_name='customer_notes',
        ),
        migrations.AddField(
            model_name='doctorsprescription',
            name='employee_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
