# Generated by Django 4.2 on 2024-04-09 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_rename_notes_doctorsprescription_customer_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('specific_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_notifcation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notifications',
            },
        ),
    ]
