# Generated by Django 4.2 on 2024-04-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('net_amount', models.CharField(max_length=10)),
                ('paid_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='billspatient', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='generated', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorsPrescription', to='dashboard.doctorsprescription')),
            ],
            options={
                'verbose_name': 'bill',
            },
        ),
        migrations.CreateModel(
            name='orderemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'orderemail',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('dosage_strength', models.CharField(max_length=255)),
                ('dose_form', models.CharField(max_length=255)),
                ('manufacture_name', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField()),
                ('qty', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('batch', models.CharField(default='0000', max_length=55)),
                ('expiry_date', models.DateField()),
                ('extra_detail', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sales',
            },
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='BillsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billitem', to='dashboard.bills')),
            ],
            options={
                'verbose_name': 'billitem',
            },
        ),
    ]
