# Generated by Django 4.2 on 2024-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_dob_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile/user.jpg', upload_to='profile'),
        ),
    ]
